environment:
  PYTHON_HOME: "C:\\Python37"

  matrix:
    - MINGW_CONFIGURATIONS: "8@x86_64@seh@posix" # bincrafters-conventions:preserve-build-job
      ARCH: x86_64
      CONAN_ARCHS: x86_64
      CPT_TEST_FOLDER: test_package_installer
      CONAN_CONANFILE: conanfile_installer.py

install:
  - set PATH=%PYTHON_HOME%;%PYTHON_HOME%/Scripts/;%PATH%
  - pip.exe install conan --upgrade
  - pip.exe install conan_package_tools bincrafters_package_tools
  - conan user # It creates the conan data directory

build_script:
  - python build.py
